-- 1. Total revenue generated by male vs female customers
select gender, sum(purchase_amount) as "Total Amount"
from customer
group by gender;

-- 2. Which customer uses discount applied but spent more than the average purchase amount
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- 3. Top 5 products with highest review ratings
select item_purchased , avg(review_rating) as "avg_rating"
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- 4. Average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) as "average_amount"
from customer
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type;

-- 5. Average spend and total revenue between subscribers and non-subscriber
select subscription_status, round(avg(purchase_amount) , 2) as average_amount , sum(purchase_amount) as total_amount
from customer
group by subscription_status;

-- 6. Which 5 products have the highest percentage of purchases with discount applied
select item_purchased , 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100 / count(*), 2) as count_of_purchase
from customer
group by item_purchased
order by count_of_purchase desc
limit 5;

-- 7. Segment customer into new, returning, and loyal based on total number of previous purchases
with customer_type as (
select customer_id, previous_purchases ,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
end as customer_segment
from customer
)

select customer_segment, count(*) as "Number_of_customers"
from customer_type
group by customer_segment;

-- 8. Top 3 most purchased products within each category
with item_category as (
	select item_purchased , category , count(item_purchased) as purchase_count , 
	row_number() over(partition by category order by count(item_purchased) desc) as item_rank
	from customer
	group by category , item_purchased
)

select item_rank , category , item_purchased , purchase_count
from item_category
where item_rank <= 3;

-- 9. Are cutomers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select count(customer_id) , subscription_status
from customer
where previous_purchases > 5
group by subscription_status;

-- 10. what is the revenue contribution of each age group
select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

select * from customer limit 25;










